config/routes.rb
Infomang::Application.routes.draw do
  resources :apikeys

  resources :users

  root :to => "home#index"

end

app/models/apikey.rb
class Apikey < ActiveRecord::Base
end

app/models/rapleafdata.rb
class Rapleafdata < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :rapleafdata, :dependent => :destroy
end

app/controllers/apikeys_controller.rb
class ApikeysController < ApplicationController
  # GET /apikeys
  # GET /apikeys.xml
  def index
    @apikeys = Apikey.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @apikeys }
    end
  end

  # GET /apikeys/1
  # GET /apikeys/1.xml
  def show
    @apikey = Apikey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @apikey }
    end
  end

  # GET /apikeys/new
  # GET /apikeys/new.xml
  def new
    @apikey = Apikey.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @apikey }
    end
  end

  # GET /apikeys/1/edit
  def edit
    @apikey = Apikey.find(params[:id])
  end

  # POST /apikeys
  # POST /apikeys.xml
  def create
    @apikey = Apikey.new(params[:apikey])

    respond_to do |format|
      if @apikey.save
        format.html { redirect_to(@apikey, :notice => 'Apikey was successfully created.') }
        format.xml  { render :xml => @apikey, :status => :created, :location => @apikey }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @apikey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /apikeys/1
  # PUT /apikeys/1.xml
  def update
    @apikey = Apikey.find(params[:id])

    respond_to do |format|
      if @apikey.update_attributes(params[:apikey])
        format.html { redirect_to(@apikey, :notice => 'Apikey was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @apikey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /apikeys/1
  # DELETE /apikeys/1.xml
  def destroy
    @apikey = Apikey.find(params[:id])
    @apikey.destroy

    respond_to do |format|
      format.html { redirect_to(apikeys_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @users }
    end
  end

    # GET /users/1
    # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user }
    end
  end

    # GET /users/new
    # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @user }
    end
  end

    # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

    # POST /users
    # POST /users.xml
  def create
    @user = User.find_or_create_by_email(params[:user][:email])
    api = RapleafApi::Api.new(Apikey.find_by_name('rapleaf').key)

    puts @user.email
    rapleaf = api.query_by_email(@user.email)

    @rapleafdata = Rapleafdata.create!(:gender => rapleaf['gender'], :country => rapleaf['country'], :age => rapleaf['age'],
                                       :city => rapleaf['city'], :state => rapleaf['state'])

    @user.rapleafdata = @rapleafdata

      #@user.rapleafdata = @rapleafdata

    respond_to do |format|
      if @user.save


        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

    # PUT /users/1
    # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

    # DELETE /users/1
    # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml { head :ok }
    end
  end
end

app/helpers/apikeys_helper.rb
module ApikeysHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apikeys/_form.html.erb
<%= form_for(@apikey) do |f| %>
  <% if @apikey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apikey.errors.count, "error") %> prohibited this apikey from being saved:</h2>

      <ul>
      <% @apikey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apikeys/edit.html.erb
<h1>Editing apikey</h1>

<%= render 'form' %>

<%= link_to 'Show', @apikey %> |
<%= link_to 'Back', apikeys_path %>

app/views/apikeys/index.html.erb
<h1>Listing apikeys</h1>

<table>
  <tr>
    <th>Key</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apikeys.each do |apikey| %>
  <tr>
    <td><%= apikey.key %></td>
    <td><%= link_to 'Show', apikey %></td>
    <td><%= link_to 'Edit', edit_apikey_path(apikey) %></td>
    <td><%= link_to 'Destroy', apikey, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Apikey', new_apikey_path %>

app/views/apikeys/new.html.erb
<h1>New apikey</h1>

<%= render 'form' %>

<%= link_to 'Back', apikeys_path %>

app/views/apikeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Key:</b>
  <%= @apikey.key %>
</p>


<%= link_to 'Edit', edit_apikey_path(@apikey) %> |
<%= link_to 'Back', apikeys_path %>

app/views/home/index.html.erb
<div id="home">

  <h1>InfoMang</h1>

  <div class="alt">Find info on anyone!</div>

  <% if !Apikey.find_by_name('rapleaf') %>
      <pre class="notice">Don't forget to add your rapleaf api key to rails. You can do this as follows.

      Boot up the rails console and type the following:
      rails console
      Apikey.create!(:name => 'rapleaf', :key => 'ENTER YOUR KEY HERE')
      </pre>
  <% end %>

  Add a user:
  <%= render 'users/form' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Infomang - Find Info on Anyone</title>


  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>


</head>
<body class="bp">

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="data">
  <div id="user-data">
    <b>Email:</b> <%= @user.email %>
    <br/>
    <% if !@user.rapleafdata.blank? %>
      <b>Age:</b> <%= @user.rapleafdata.age %>
      <br/>
      <b>Gender:</b> <%= @user.rapleafdata.gender %></br>
      <b>City:</b> <%= @user.rapleafdata.city %></br>
      <b>State:</b> <%= @user.rapleafdata.state %></br>
      <b>Country:</b> <%= @user.rapleafdata.country %></br>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>